export const DAYS_AMOUNT_OF_CALENDAR = 42
export const WEEKDAYS = ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su']
export const BASE_DATE_FORMAT = 'M-D-YYYY'
export const BASE_DATE_FORMAT_WITH_TIME = 'M-D-YYYY HH:mm'
export const DISPLAY_DATE_FORMAT = 'MMM D, YYYY'
export const DISPLAY_DATE_FORMAT_WITH_TIME = 'MMM D, YYYY HH:mm'
export const ARROW_UP = 'ArrowUp'
export const ARROW_RIGHT = 'ArrowRight'
export const ARROW_DOWN = 'ArrowDown'
export const ARROW_LEFT = 'ArrowLeft'
export const ENTER = 'Enter'
export const HHMM = 'HH:mm'
export const DEFAULT_TIME = '0:00'
